eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost1:8761/eureka/}
  instance:
   prefer-ip-address: true

okta:
 oauth2:
  issuer: https://dev-30717030.okta.com/oauth2/default
  audience: api://default
